### ISSUE TITLE
Does the game still work?

### ISSUE THREAD

**Issue by husujo** [chessmasterhong/WaterEmblem#205]
I'd like to try it out, but I see that' it's 2 years old, and there are things in the .gitignore that I'm not sure if I need to run it. The README doesn't really describe how to run it either. If not, it's fine, just really curious to try it! :)

**Comment by chessmasterhong** [comment]
It seems the link to the demo was outdated. I have updated the link on the front-page of this repo. For convenience, it is [here](https://chessmasterhong.bitbucket.io/projects/WaterEmblem/). The game still works as the the deployed code has not changed since then. We hope you enjoy!

In regards to trying to run the game yourself: The game requires [ImpactJS](http://impactjs.com/) to develop or run. As it is not free or open source, we cannot include the code. Furthermore, our team had opted not to distribute the media files as noted in the [disclaimer](https://github.com/chessmasterhong/WaterEmblem#disclaimer) in the README. The rest of the .gitignore is a simple server file for local development and other temporary files.

**Comment by husujo** [comment]
Ok, it works now! Looks really cool. Thanks for updating the link!
