### ISSUE TITLE
Unequip button no longer works properly

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#89]
Choosing to unequip a weapon no longer functions as it should. By attempting to unequip the currently equipped weapon, it will not actually unequip it. When going into battle, it will still show that weapon as being equipped, and the player's stats do not actually revert when trying to unequip said weapon.

**Comment by chessmasterhong** [comment]
How? What is its function now that is different than its intended function? More details are necessary.

**Comment by chessmasterhong** [comment]
To clarify for future references: Previously, item slot 0 was exclusively designated for the unit's currently equipped weapon. Due to the proposed revision as described in issue #91, slot 0 now will be overhauled to accept non-equippable items but will not register the items as equipped if it is not a weapon or if the weapon does not match the unit's equippable weapon types. Equipped weapons for each unit will now be denoted with an [E] indicator to the equipped item name in the unit's inventory.
