### ISSUE TITLE
Trading items with another player unit does not check if item is a valid equipable item.

### ISSUE THREAD

**Issue by chessmasterhong** [chessmasterhong/WaterEmblem#91]
Currently, any item can be traded into another player unit's equipment slot (slot 0) without restrictions. This can result in units equipping items that they should not be able to equip. The restriction of unit-specific item type equips was put into place by pull request #67.

Ideally, the objective is to extend the checks implemented in #67 to the trade system.

Below shows an example of a mage unit (right side) equipping a bow when it was specifically coded to only equip tomes. Even weirder is a unit (left side) equipping a consumable item.

![capture](https://cloud.githubusercontent.com/assets/1214945/5706536/ccc2b7b6-9a4f-11e4-96c8-3569f6bdd073.JPG)

**Comment by DrkSephy** [comment]
There are a few ways we can go about this. Keeping in mind that we originally intended for slot 0 to be the equipped item slot:

1. One possibility is that the above behavior is completely fine. However, we would have to make sure that if an item is traded into slot 0, the `recomputeStats` function should not be executed; i.e: The unit receiving the item doesn't auto-equip the new item. (This is preferable). 

2. We prevent the player from trading into slot 0 entirely.

3. We prevent the player from trading invalid weapons into slot 0, but at the same time making sure that the `recomputeStats` function isn't executed. The reason for this is because we decided it would make certain elements too easy if you could just trade in an item to the first slot.

4. We repeat (1), allowing the player to trade items into slot 0. However, this time we will call `recomputeStats` only if the item in slot 0 is valid for that unit.

Out of all of these, my vote goes with (1).

**Comment by DrkSephy** [comment]
After discussing the issue with @chessmasterhong, we have decided to go with this method:

1. Players can trade items into any slot. 
2. We always call recomputeStats, which acts on the first item. If it is valid, it will be equipped. Otherwise, no.
3. If the item can be equipped, we append an [E] to the item name to show that it is equipped. Other possibilities include changing color of the text, etc. More options can be explored in the future.

**Comment by chessmasterhong** [comment]
Pull request #92 implements item 1 and 2, but not 3 as indicated by @DrkSephy. Once item 3 is implemented, we will close this issue.

**Comment by DrkSephy** [comment]
Pull request #92 currently addresses item 3 now. 
![new_equip](https://cloud.githubusercontent.com/assets/1226900/5714637/d96642c2-9a99-11e4-9dc8-398cd0576bae.png)
